query findPendingTrades {
  biscoint_trade(where: {type: {_eq: "arbitrage"}, status: {_in: ["open", "broken"]}}) {
    closeOffer {
      apiKeyId
      base
      baseAmount
      confirmedAt
      createdAt
      efPrice
      expiresAt
      id
      isQuote
      offerId
      op
      quote
      quoteAmount
    }
    id
    checkedAt
    openOffer {
      apiKeyId
      base
      baseAmount
      confirmedAt
      createdAt
      efPrice
      expiresAt
      id
      isQuote
      offerId
      op
      quote
      quoteAmount
    }
    owner
    status
    strategy
    type
  }
}
