mutation updateTrade($id: Int!, $checkedAt: timestamptz, $status: String, $hasSiblings: Boolean, $closeOfferId: Int) {
  update_biscoint_trade_by_pk(pk_columns: {id: $id}, _set: {checkedAt: $checkedAt, status: $status, hasSiblings: $hasSiblings, closeOfferId: $closeOfferId}) {
    id
  }
}
